### ISSUE TITLE
'MixLibOne-Swift.h' file not found

### ISSUE THREAD

**Issue by wulongwang** [ashislaha/Swift-ObjectiveC-Interoperability#1]
1、clone Swift-ObjectiveC-Interoperability 
2、open PlayWithLibraries.xcodeproj
3、select iPhone 11 Simulator
show the blew error 
 how to fix ?
![image](https://user-images.githubusercontent.com/3376097/83013925-5e692b80-a050-11ea-8805-a4f3665198e0.png)

**Comment by ashislaha** [comment]
hey, thanks for pointing it out. check the latest commit or sync with master again. it's solved. There was a conflict & due to that App Target was not building. Also, check the .readme to understand the multiple target dependencies.
