### ISSUE TITLE
Not bug 

### ISSUE THREAD

**Issue by wulongwang** [ashislaha/Swift-ObjectiveC-Interoperability#2]
Hi ashislaha, I copy you project 'Swift-ObjectiveC-Interoperability' to my github, I want to redesign, so  I have to make it clear to you，If you don't allow it, I'll delete it. Thanks

My github address
https://github.com/wulongwang/Swift-ObjectiveC-Interoperability

I add you github reference story at the end of the REAMME.md
![image](https://user-images.githubusercontent.com/3376097/88500278-c7dacb80-cffa-11ea-972e-9f10a4b10201.png)

**Comment by ashislaha** [comment]
sure. no problem. go ahead. thanks!
